// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityGroupPolicy) DeepCopyInto(out *SecurityGroupPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityGroupPolicy.
func (in *SecurityGroupPolicy) DeepCopy() *SecurityGroupPolicy {
	if in == nil {
		return nil
	}
	out := new(SecurityGroupPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecurityGroupPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityGroupPolicyList) DeepCopyInto(out *SecurityGroupPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SecurityGroupPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityGroupPolicyList.
func (in *SecurityGroupPolicyList) DeepCopy() *SecurityGroupPolicyList {
	if in == nil {
		return nil
	}
	out := new(SecurityGroupPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecurityGroupPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityGroupPolicyPodSelector) DeepCopyInto(out *SecurityGroupPolicyPodSelector) {
	*out = *in
	if in.MatchLabels != nil {
		in, out := &in.MatchLabels, &out.MatchLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityGroupPolicyPodSelector.
func (in *SecurityGroupPolicyPodSelector) DeepCopy() *SecurityGroupPolicyPodSelector {
	if in == nil {
		return nil
	}
	out := new(SecurityGroupPolicyPodSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityGroupPolicySecurityGroups) DeepCopyInto(out *SecurityGroupPolicySecurityGroups) {
	*out = *in
	if in.GroupIDs != nil {
		in, out := &in.GroupIDs, &out.GroupIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityGroupPolicySecurityGroups.
func (in *SecurityGroupPolicySecurityGroups) DeepCopy() *SecurityGroupPolicySecurityGroups {
	if in == nil {
		return nil
	}
	out := new(SecurityGroupPolicySecurityGroups)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityGroupPolicySpec) DeepCopyInto(out *SecurityGroupPolicySpec) {
	*out = *in
	in.PodSelector.DeepCopyInto(&out.PodSelector)
	in.SecurityGroups.DeepCopyInto(&out.SecurityGroups)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityGroupPolicySpec.
func (in *SecurityGroupPolicySpec) DeepCopy() *SecurityGroupPolicySpec {
	if in == nil {
		return nil
	}
	out := new(SecurityGroupPolicySpec)
	in.DeepCopyInto(out)
	return out
}
