name: "Provision PostgreSQL"
description: "Adds a databases entry to the cluster.yaml and runs apply cluster"

inputs:
  cluster-manifest-path:
    description: Path to the cluster manifest
    required: true
  okctl-path:
    description: Path to the okctl binary
    required: true
  aws-access-key-id:
    description: AWS service user access key ID
    required: true
  aws-secret-access-key:
    description: AWS service user secret access key
    required: true
  github-token:
    description: Github authentication token
    required: true
  database-name:
    description: Name of the database to provision
    required: true

runs:
  using: "composite"
  steps:
    - name: Add databases entry
      run: |
        yq eval -i '.databases.postgres[0] = {"name": "${{ inputs.database-name }}", "namespace": "nightlydb", "user": "postgres"}' ${{ inputs.cluster-manifest-path }}
      shell: bash
    - name: Apply cluster
      run: |
        ${{ inputs.okctl-path }} apply cluster \
          --file ${{ inputs.cluster-manifest-path }} \
          --no-spinner
      env:
        OKCTL_AWS_CREDENTIALS_TYPE: access-key
        OKCTL_GITHUB_CREDENTIALS_TYPE: token
        AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
        OKCTL_DEBUG: 'true'
        OKCTL_METRICS_USERAGENT: okctldev
      shell: bash
